### ISSUE TITLE
Criação das Tabelas

### ISSUE THREAD

**Issue by Incivius** [projetoKhali/api4back#14]
# Necessidade:
`Qual iniciativa precisa ser trabalhada?`

- Criar as tabelas no banco de dados conforme a modelagem definida projetoKhali/api4back#6 

# Motivação:
`Por que precisamos dessa mudança?`

-  Garantir a existência das estruturas necessárias para armazenar os dados de forma adequada.

# Critérios de aceite:
`Quais parâmetros devem ser atendidos?`

- Tabelas criadas com os campos especificados e relacionamentos definidos.

**Comment by paulo-granthon** [comment]
esse issue não é resolvido pelo #2 também?
