### ISSUE TITLE
feat: `view` de métricas da `Track` no banco de dados

### ISSUE THREAD

**Issue by paulo-granthon** [projetoKhali/api4back#31]
# Necessidade:
`Qual iniciativa precisa ser trabalhada?`

- Criação de uma `view` no banco de dados com a finalidade de compilar todos os dados comparativos do contexto `Track`.

# Motivação:
`Por que precisamos dessa mudança?`

- Disponibilizar métricas compiladas para comparação entre tracks e geração de gráficos relatórios.

# Critérios de aceite:
`Quais parâmetros devem ser atendidos?`

- Criação da view de `track_metrics` no DDL do banco de dados, responsável por fazer a compilação dos dados da track;
- Talvez seja necessário a criação de uma nova classe `Entity` para representar o objeto retornado da view, assim como seu `Repository` correspondente. (é necessário avaliar durante a implementação);

**Comment by JhonatanLop** [comment]
além da view. foi adicionado o back-end de mapeamento da view

consulta por id da track
![image](https://github.com/projetoKhali/api4back/assets/111443621/67d12c52-0fb9-4131-ab88-6a62c2b99dcb)

consulta em todas
![image](https://github.com/projetoKhali/api4back/assets/111443621/a20c9127-d5a6-4796-a00f-6654c4c56d85)
