### ISSUE TITLE
Update view track

### ISSUE THREAD

**Issue by Incivius** [projetoKhali/api4back#57]
# Necessidade:
`Qual iniciativa precisa ser trabalhada?`

- Incluir mais algumas métricas dentro da view track metrics e retorna-las através do endpoint

# Motivação:
`Por que precisamos dessa mudança?`

- Utilizaremos essas informações dentro do dashboard comparativo

# Critérios de aceite:
`Quais parâmetros devem ser atendidos?`

A view deve possuir as seguintes colunas:

- [ ] Nome da track
- [x] Total de expertises
- [x] Total de qualificadores
- [x] Total de parceiros
- [x] Tempo Médio de conclusão da expertise
- [x] Tempo médio de conclusão dos qualificadores
- [x] Média de conclusão dos qualificadores
- [x] Média de conclusão das expertises
- [ ] Média de conclusão da track (Média de qualificadores e Expertises)
- [ ] Tempo médio de conclusão da track
- [ ] Abandono (Numero de qualificadores vencidos)

# Sugestões:
`Observações para obter mais facilidade e / ou qualidade na implementação`

![image](https://github.com/projetoKhali/api4back/assets/111438883/b7592d9a-7aab-4a55-9440-e88a7b78896f)

**Comment by JhonatanLop** [comment]
Entendimento da task:

[ ] Média de conclusão dos qualificadores

Fazer a média de qualificadores concluídos de uma track. Analizar o total de qualificadores que devem ser feitos por todos os usuário que escolheram a track (e as expertizes da track) e fazer uma média entre total é concluídas

[ ] Média de conclusão das expertises

Fazer a média de conclusão das expertises de uma track. Analizar o total de expertizes que foram escolhidas pelos usuários e fazer a média entre total e concluídas.

correto?
@Incivius

**Comment by Incivius** [comment]
[ ] Nome da track
[X] Número de parceiros
[ ] Abandono (Numero de qualificadores vencidos)
[ ] Média de conclusão da track (Média de qualificadores e Expertises)
[ ] Tempo médio de conclusão da track
[X] Quantidade de expertises por track
[X] Quantidade de qualificadores por track
[X] Tempo médio de conclusão de expertises por track
[X] Tempo médio de conclusão de qualificadores por tracks
[ ] Média de conclusão de expertises
[ ] Média de conclusão de qualifiers

**Comment by Incivius** [comment]
Abandono = Data de conclusão do qualificador + 1 ano < data atual = vencido

**Comment by JhonatanLop** [comment]
atualização da atividade

lista de colunas:

[X] Nome da track
[X] Total de expertises
[X] Total de qualificadores
[X] Total de parceiros
[X] Tempo Médio de conclusão da expertise
[X] Tempo médio de conclusão dos qualificadores
[X] Média de conclusão dos qualificadores
[X] Média de conclusão das expertises
[X] Abandono (Numero de qualificadores vencidos)
[ ] Média de conclusão da track (Média de qualificadores e Expertises)
[ ] Tempo médio de conclusão da track
